service: pipes
frameworkVersion: '>=2.7'

# TODO: extract to .env
custom:
    region: eu-west-1
    stage: prod

provider:
    lambdaHashingVersion: 20201221
    name: aws
    region: ${self:custom.region}
    stage: ${self:custom.stage}
    runtime: provided.al2
    environment:
        APP_ENV: prod
    httpApi:
        disableDefaultEndpoint: true
        useProviderTags: true
    tags:
        vendor: sigwin
        project: pipes

constructs:
    routes:
        type: database/dynamodb-single-table

plugins:
  - ./vendor/bref/bref
  - serverless-lift
functions:
    web:
        handler: App\Infrastructure\Symfony\Kernel
        timeout: 1
        layers:
            - ${bref:layer.php-81}
        environment:
            APP_AWS_DYNAMODB_TABLENAME: ${construct:routes.tableName}
            BREF_LOOP_MAX: 100
        events:
            -
                httpApi: '*'

package:
    patterns:
        # Excluded files and folders for deployment
        - '!.idea/**'
        - '!.infra/**'
        - '!assets/**'
        - '!node_modules/**'
        - '!public/build/**'
        - '!tests/**'
        - '!var/**'
        - '!.dockerignore'
        - '!.env'
        - '!.php-version'
        - '!composer.lock'
        - '!Makefile'
        - '!symfony.lock'
        # If you want to include files and folders that are part of excluded folders,
        # add them at the end
        - 'var/cache/prod/**'
        - 'public/build/entrypoints.json'
        - 'public/build/manifest.json'
