services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\EventConverter:
            tags:
                - name: pipes.event_converter

    App\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/Symfony/Kernel.php'

    App\Infrastructure\Symfony\Controller\:
        resource: '../src/Infrastructure/Symfony/Controller'
        tags: [ 'controller.service_arguments' ]

    App\EventExchange:
        $converters: !tagged pipes.event_converter
