services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $tableName: "%env(AWS_DYNAMODB_TABLENAME)%"

    App\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/Symfony/Kernel.php'

    Psr\Http\Message\RequestFactoryInterface: '@psr18.http_client'
    Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory: ~
